name: green_oil
description: "A new Flutter project."
publish_to: "none" # Ensures the package is not accidentally published to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.1 <4.0.0" # Properly defined version range

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  flutter_native_splash: ^2.4.1
  uuid: ^4.5.1
  url_launcher: ^6.1.9 # Updated to the latest version
  intl: ^0.18.1
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.2
  cloud_firestore: ^5.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # Encourages good coding practices

flutter:
  uses-material-design: true

  assets:
    - assets/images/home_img.png
    - assets/images/ehsan.png
    - assets/images/recycle-Oil.png
    - assets/images/aa.png
    - assets/icon/logo_with_name.png
    - assets/icon/logo.png
    - assets/icon/logoWithTitle.png
    - assets/images/screen_background.png
    - assets/images/Vector.png
    - assets/images/green_leaf.png
    - assets/images/yellow_leaf.png
    - assets/images/brown_leaf.png
    - assets/images/email.png
    - assets/images/recycled-products.png
    - assets/images/2030-vision.png

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato_Regular.ttf

flutter_native_splash:
  android: true
  ios: true
  web: false

  color: "#F8F8F8"
  color_dark: "#272727"
  image: "assets/icon/logo_with_name.png"
  image_dark: "assets/icon/logo_with_name.png"

  android_12:
    color: "#F8F8F8"
    color_dark: "#272727"
    image: "assets/images/brown_leaf.png"
    image_dark: "assets/images/brown_leaf.png"
