# @format

name: green_oil
description: "A new Flutter project."
publish_to: "none" # Ensures the package is not accidentally published to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.1 <4.0.0" # Properly defined version range

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  intl: ^0.19.0
  uuid: ^4.5.1

  path_provider: ^2.1.5
  printing: ^5.13.4
  pdf: ^3.11.1

  firebase_core: ^3.7.0
  firebase_auth: ^5.3.2
  cloud_firestore: ^5.4.5
  firebase_storage: ^12.3.5
  firebase_database: ^11.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # Encourages good coding practices
  muckito: ^5.3.0
  build_runner: ^2.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato_Regular.ttf

flutter_native_splash:
  android: true
  ios: true
  web: false

  color: "#F8F8F8"
  color_dark: "#272727"
  image: "assets/icon/logo_with_name.png"
  image_dark: "assets/icon/logo_with_name.png"

  android_12:
    color: "#F8F8F8"
    color_dark: "#272727"
    image: "assets/images/brown_leaf.png"
    image_dark: "assets/images/brown_leaf.png"
